[env:seeed_xiao_esp32s3]
platform = espressif32@6.3.2
board = seeed_xiao_esp32s3
framework = arduino

monitor_speed   = 115200
monitor_filters = direct
upload_speed    = 921600

board_build.mcu   = esp32s3
board_build.f_cpu = 240000000L

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1

lib_ignore =
    DoubleResetDetect
    ESP_DoubleResetDetector

lib_ldf_mode    = chain
lib_compat_mode = strict

lib_deps =
    adafruit/Adafruit BusIO @ ^1.14.1
    adafruit/Adafruit SSD1306 @ ^2.5.7
    adafruit/Adafruit GFX Library @ ^1.11.5
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library @ ^1.1.2
    mobizt/Firebase ESP32 Client